default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sh("open","/Users/qoli/GitHub/AtomicR/Update/Update.md")
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
  	increment_build_number
    build_app(
    	workspace: "Router.xcworkspace",
    	scheme: "Router",
    	xcargs: "-UseModernBuildSystem=0"
    	)
    upload_to_testflight(
      changelog: "by fastlane upload",
      distribute_external: true,
      groups: "Open Beta"
      )
    sh("date > /Users/qoli/GitHub/AtomicR/Update/updatetime.txt")
    sh("git","add",".")
    sh("git","commit","$(date)")
    sh("git","pull")
  end

end
