default_platform(:ios)

platform :ios do
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    
    sh("open","/Users/qoli/GitHub/AtomicR/Update/Update.md")
    sh("open","/Users/qoli/GitHub/AtomicR/Update/changelog.txt")
    xcode_select("/Applications/Xcode-beta.app")
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
  	increment_build_number
    build_app(
    	workspace: "Router.xcworkspace",
    	scheme: "Router"
    	)
    changelog = File.read("/Users/qoli/GitHub/AtomicR/Update/changelog.txt")
    upload_to_testflight(
      changelog: changelog,
      distribute_external: true,
      groups: "Open Beta"
      )
  end

  desc "Push a new release build to the App Store"
  lane :store do
    sh("open","./changelog.txt")
    xcode_select("/Applications/Xcode.app")
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number
    build_app(workspace: "Router.xcworkspace", scheme: "Router")
    cp("cp -i","/Users/qoli/Documents/Xcode/Router/fastlane/changelog.txt","/Users/qoli/Documents/Xcode/Router/fastlane/metadata/en-US/release_notes.txt")
    cp("cp -i","/Users/qoli/Documents/Xcode/Router/fastlane/changelog.txt","/Users/qoli/Documents/Xcode/Router/fastlane/metadata/zh-Hans/release_notes.txt")
    cp("cp -i","/Users/qoli/Documents/Xcode/Router/fastlane/changelog.txt","/Users/qoli/Documents/Xcode/Router/fastlane/metadata/zh-Hant/release_notes.txt")
    upload_to_app_store(
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true
    )
  end

end
